// <auto-generated />
using System;
using Amiquin.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amiquin.MySql.Migrations
{
    [DbContext(typeof(AmiquinContext))]
    partial class AmiquinContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Amiquin.Core.Models.BotStatistics", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<float>("AvailableMemoryMB")
                        .HasColumnType("float");

                    b.Property<double>("AverageCommandExecutionTimeInMs")
                        .HasColumnType("double");

                    b.Property<string>("BotName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CacheItems")
                        .HasColumnType("int");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Latency")
                        .HasColumnType("int");

                    b.Property<int>("ShardCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalChannelsCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalCommandsCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalErrorsCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalServersCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalUsersCount")
                        .HasColumnType("int");

                    b.Property<int>("UpTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<float>("UsedMemoryMB")
                        .HasColumnType("float");

                    b.Property<float>("UsedMemoryPercentage")
                        .HasColumnType("float");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BotStatistics");
                });

            modelBuilder.Entity("Amiquin.Core.Models.ChatSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Context")
                        .HasColumnType("longtext");

                    b.Property<int>("ContextTokens")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstimatedTokens")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<ulong>("OwningEntityId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<ulong?>("ServerId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ChatSessions_Created");

                    b.HasIndex("ServerId");

                    b.HasIndex("IsActive", "LastActivityAt")
                        .HasDatabaseName("IX_ChatSessions_Activity");

                    b.HasIndex("Scope", "OwningEntityId")
                        .HasDatabaseName("IX_ChatSessions_Scope_Owner");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("Amiquin.Core.Models.CommandLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CommandDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("ServerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("CommandLogs");
                });

            modelBuilder.Entity("Amiquin.Core.Models.ConversationMemory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessCount")
                        .HasColumnType("int");

                    b.Property<string>("ChatSessionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EstimatedTokens")
                        .HasColumnType("int");

                    b.Property<float>("ImportanceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ConversationMemories_Created");

                    b.HasIndex("ImportanceScore")
                        .HasDatabaseName("IX_ConversationMemories_Importance");

                    b.HasIndex("ChatSessionId", "MemoryType")
                        .HasDatabaseName("IX_ConversationMemories_SessionType");

                    b.ToTable("ConversationMemories");
                });

            modelBuilder.Entity("Amiquin.Core.Models.GlobalToggle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("AllowServerOverride")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GlobalToggles");
                });

            modelBuilder.Entity("Amiquin.Core.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Amiquin.Core.Models.NachoPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NachoCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("NachoReceivedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("ServerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("NachoPacks");
                });

            modelBuilder.Entity("Amiquin.Core.Models.PaginationSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("int");

                    b.Property<string>("EmbedData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_PaginationSessions_UserActive");

                    b.ToTable("PaginationSessions");
                });

            modelBuilder.Entity("Amiquin.Core.Models.ServerMeta", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("NsfwChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredProvider")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("PrimaryChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServerMetas");
                });

            modelBuilder.Entity("Amiquin.Core.Models.SessionMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChatSessionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiscordMessageId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EstimatedTokens")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeInContext")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DiscordMessageId");

                    b.ToTable("SessionMessages");
                });

            modelBuilder.Entity("Amiquin.Core.Models.Toggle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Toggles");
                });

            modelBuilder.Entity("Amiquin.Infrastructure.Entities.UserStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FunStatsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fun_stats");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ServerId")
                        .IsUnique();

                    b.ToTable("user_stats");
                });

            modelBuilder.Entity("Amiquin.Core.Models.ChatSession", b =>
                {
                    b.HasOne("Amiquin.Core.Models.ServerMeta", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Amiquin.Core.Models.CommandLog", b =>
                {
                    b.HasOne("Amiquin.Core.Models.ServerMeta", "Server")
                        .WithMany("CommandLogs")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Amiquin.Core.Models.ConversationMemory", b =>
                {
                    b.HasOne("Amiquin.Core.Models.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Amiquin.Core.Models.Message", b =>
                {
                    b.HasOne("Amiquin.Core.Models.ServerMeta", "Server")
                        .WithMany("Messages")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Amiquin.Core.Models.NachoPack", b =>
                {
                    b.HasOne("Amiquin.Core.Models.ServerMeta", "Server")
                        .WithMany("NachoPacks")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Amiquin.Core.Models.SessionMessage", b =>
                {
                    b.HasOne("Amiquin.Core.Models.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Amiquin.Core.Models.Toggle", b =>
                {
                    b.HasOne("Amiquin.Core.Models.ServerMeta", "Server")
                        .WithMany("Toggles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Amiquin.Core.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Amiquin.Core.Models.ServerMeta", b =>
                {
                    b.Navigation("CommandLogs");

                    b.Navigation("Messages");

                    b.Navigation("NachoPacks");

                    b.Navigation("Toggles");
                });
#pragma warning restore 612, 618
        }
    }
}
