#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Production deployment script for Amiquin Discord bot
.DESCRIPTION
    Comprehensive production deployment script that handles:
    - Environment validation
    - Security configuration
    - Performance optimization
    - Service orchestration
    - Health monitoring
    - Backup configuration
#>

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("mysql", "sqlite")]
    [string]$DatabaseType = "mysql",
    
    [Parameter(Mandatory=$false)]
    [string]$Environment = "production",
    
    [Parameter(Mandatory=$false)]
    [string]$InstanceName = "amiquin-prod",
    
    [switch]$SkipBuild,
    [switch]$SkipHealthCheck,
    [switch]$EnableMonitoring,
    [switch]$EnableBackups,
    [switch]$DryRun,
    [switch]$Help
)

if ($Help) {
    Write-Host "Amiquin Production Deployment Script" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "This script deploys Amiquin to production with:"
    Write-Host "  - Security hardening and authentication"
    Write-Host "  - Performance optimization"
    Write-Host "  - Monitoring and health checks"
    Write-Host "  - Backup and disaster recovery"
    Write-Host "  - SSL/TLS configuration"
    Write-Host ""
    Write-Host "Usage:"
    Write-Host "  ./deploy-production.ps1 -DatabaseType mysql -Environment production"
    Write-Host "  ./deploy-production.ps1 -SkipBuild -EnableMonitoring"
    Write-Host "  ./deploy-production.ps1 -DryRun  # Validate configuration without deploying"
    Write-Host ""
    Write-Host "Parameters:"
    Write-Host "  -DatabaseType    mysql|sqlite (default: mysql)"
    Write-Host "  -Environment     Target environment (default: production)"
    Write-Host "  -InstanceName    Instance identifier (default: amiquin-prod)"
    Write-Host "  -SkipBuild       Skip application build step"
    Write-Host "  -SkipHealthCheck Skip health check validation"
    Write-Host "  -EnableMonitoring Enable monitoring stack (Prometheus/Grafana)"
    Write-Host "  -EnableBackups   Enable automated backups"
    Write-Host "  -DryRun          Validate configuration without deploying"
    exit 0
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

Write-Host "=== Amiquin Production Deployment ===" -ForegroundColor Cyan
Write-Host "Environment: $Environment" -ForegroundColor Green
Write-Host "Instance: $InstanceName" -ForegroundColor Green
Write-Host "Database: $DatabaseType" -ForegroundColor Green
Write-Host ""

# Navigate to project root
Set-Location $ProjectRoot

# Validation Functions
function Test-Prerequisites {
    Write-Host "Checking prerequisites..." -ForegroundColor Cyan
    
    $errors = @()
    
    # Check Docker
    try {
        $null = docker info 2>$null
        Write-Host "✓ Docker is running" -ForegroundColor Green
    } catch {
        $errors += "Docker is not running or not installed"
    }
    
    # Check Docker Compose
    try {
        $null = docker-compose --version 2>$null
        Write-Host "✓ Docker Compose is available" -ForegroundColor Green
    } catch {
        $errors += "Docker Compose is not installed"
    }
    
    # Check .env file
    if (Test-Path ".env") {
        Write-Host "✓ Environment file exists" -ForegroundColor Green
    } else {
        $errors += ".env file is missing - run setup-project.ps1 first"
    }
    
    # Check required environment variables
    $requiredVars = @(
        "AMQ_Discord__Token",
        "AMQ_LLM__Providers__OpenAI__ApiKey"
    )
    
    $envContent = Get-Content ".env" -ErrorAction SilentlyContinue
    foreach ($var in $requiredVars) {
        $found = $envContent | Where-Object { $_ -match "^$var=" -and $_ -notmatch "your-.*-here" }
        if ($found) {
            Write-Host "✓ $var is configured" -ForegroundColor Green
        } else {
            $errors += "$var is not configured in .env file"
        }
    }
    
    if ($errors.Count -gt 0) {
        Write-Host "❌ Prerequisites check failed:" -ForegroundColor Red
        foreach ($error in $errors) {
            Write-Host "  • $error" -ForegroundColor Red
        }
        exit 1
    }
    
    Write-Host "✓ All prerequisites satisfied" -ForegroundColor Green
    Write-Host ""
}

function Set-ProductionEnvironment {
    Write-Host "Configuring production environment..." -ForegroundColor Cyan
    
    # Create production environment overrides
    $prodEnvContent = @"
# Production Environment Overrides
# Generated by deploy-production.ps1

# Production Environment
ASPNETCORE_ENVIRONMENT=Production
DOTNET_ENVIRONMENT=Production

# Performance Optimizations
DOTNET_GCServer=true
DOTNET_GCConcurrent=true
DOTNET_GCRetainVM=true
DOTNET_TieredCompilation=true
DOTNET_TieredPGO=1
DOTNET_TC_QuickJitForLoops=1

# Security Hardening
ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
ASPNETCORE_PATHBASE=
ASPNETCORE_PREVENTHOSTINGSTARTUP=true

# Resource Limits
AMIQUIN_MEMORY_LIMIT=2G
AMIQUIN_MEMORY_RESERVATION=512M
QDRANT_MEMORY_LIMIT=4G
QDRANT_MEMORY_RESERVATION=2G

# MySQL Version (tuning is done via mysql/conf.d/production.cnf)
MYSQL_VERSION=8.0

# Qdrant Production Settings
QDRANT_VERSION=v1.7.4
QDRANT_MAX_REQUEST_SIZE_MB=64
QDRANT_MAX_WORKERS=0
QDRANT_WAL_CAPACITY_MB=64
QDRANT_DEFAULT_SEGMENT_NUMBER=2
QDRANT_MEMMAP_THRESHOLD_KB=200000
QDRANT_INDEXING_THRESHOLD_KB=20000
QDRANT_HNSW_M=16
QDRANT_HNSW_EF_CONSTRUCT=100
QDRANT_TELEMETRY_DISABLED=true

# Build Configuration
BUILD_CONFIGURATION=Release

# Instance Configuration
AMQ_BOT_NAME=$InstanceName

"@

    Set-Content -Path ".env.production" -Value $prodEnvContent -Encoding UTF8
    Write-Host "✓ Production environment configuration created" -ForegroundColor Green
}

function Invoke-ProductionBuild {
    if ($SkipBuild) {
        Write-Host "Skipping build (--SkipBuild specified)" -ForegroundColor Yellow
        return
    }
    
    Write-Host "Building application for production..." -ForegroundColor Cyan
    
    # Clean previous builds
    if (Test-Path "source/Amiquin.Bot/bin") {
        Remove-Item "source/Amiquin.Bot/bin" -Recurse -Force
    }
    if (Test-Path "source/Amiquin.Bot/obj") {
        Remove-Item "source/Amiquin.Bot/obj" -Recurse -Force
    }
    
    # Build application
    Set-Location "source"
    try {
        Write-Host "Restoring NuGet packages..." -ForegroundColor Cyan
        dotnet restore source.sln --configuration Release
        
        Write-Host "Building solution..." -ForegroundColor Cyan
        dotnet build source.sln --configuration Release --no-restore
        
        Write-Host "Running tests..." -ForegroundColor Cyan
        dotnet test source.sln --configuration Release --no-build --logger "console;verbosity=minimal"
        
        Write-Host "✓ Build completed successfully" -ForegroundColor Green
    } catch {
        Write-Host "❌ Build failed" -ForegroundColor Red
        exit 1
    } finally {
        Set-Location $ProjectRoot
    }
}

function Start-ProductionServices {
    Write-Host "Starting production services..." -ForegroundColor Cyan
    
    if ($DryRun) {
        Write-Host "DRY RUN: Would execute: docker-compose --env-file .env.production --profile prod up -d" -ForegroundColor Yellow
        return
    }
    
    # Start core production stack
    try {
        Write-Host "Starting core services (MySQL, Qdrant, Amiquin)..." -ForegroundColor Cyan
        docker-compose --env-file .env --env-file .env.production --profile prod up -d
        
        Write-Host "✓ Core services started" -ForegroundColor Green
        
        # Optional monitoring stack
        if ($EnableMonitoring) {
            Write-Host "Starting monitoring services..." -ForegroundColor Cyan
            docker-compose --env-file .env --env-file .env.production --profile monitoring up -d
            Write-Host "✓ Monitoring services started" -ForegroundColor Green
        }
        
    } catch {
        Write-Host "❌ Failed to start services" -ForegroundColor Red
        exit 1
    }
}

function Test-ServiceHealth {
    if ($SkipHealthCheck) {
        Write-Host "Skipping health checks (--SkipHealthCheck specified)" -ForegroundColor Yellow
        return
    }
    
    Write-Host "Performing health checks..." -ForegroundColor Cyan
    
    $services = @(
        @{Name="MySQL"; Container="mysql-$InstanceName"; Port=3306; Timeout=60},
        @{Name="Qdrant"; Container="qdrant-$InstanceName"; Port=6333; Timeout=30},
        @{Name="Amiquin Bot"; Container="bot-$InstanceName"; Port=10000; Timeout=120}
    )
    
    foreach ($service in $services) {
        Write-Host "Checking $($service.Name)..." -ForegroundColor Cyan
        
        $timeout = $service.Timeout
        $elapsed = 0
        
        do {
            try {
                $status = docker inspect --format='{{.State.Health.Status}}' $service.Container 2>$null
                if ($status -eq "healthy") {
                    Write-Host "✓ $($service.Name) is healthy" -ForegroundColor Green
                    break
                } elseif ($status -eq "unhealthy") {
                    Write-Host "❌ $($service.Name) is unhealthy" -ForegroundColor Red
                    docker logs --tail 20 $service.Container
                    exit 1
                }
            } catch {
                # Container might not exist yet
            }
            
            Start-Sleep 5
            $elapsed += 5
            
            if ($elapsed -ge $timeout) {
                Write-Host "❌ $($service.Name) health check timed out after $timeout seconds" -ForegroundColor Red
                docker logs --tail 20 $service.Container
                exit 1
            }
            
            Write-Host "  Waiting for $($service.Name)... ($elapsed/$timeout seconds)" -ForegroundColor Yellow
        } while ($true)
    }
    
    Write-Host "✓ All services are healthy" -ForegroundColor Green
}

function Show-DeploymentSummary {
    Write-Host ""
    Write-Host "=== Deployment Complete ===" -ForegroundColor Green
    Write-Host ""
    
    Write-Host "Production Services:" -ForegroundColor Cyan
    Write-Host "  • MySQL Database: localhost:3306"
    Write-Host "  • Qdrant Vector DB: localhost:6333 (REST), localhost:6334 (gRPC)"
    Write-Host "  • Amiquin Bot: localhost:10001"
    
    if ($EnableMonitoring) {
        Write-Host ""
        Write-Host "Monitoring Services:" -ForegroundColor Cyan
        Write-Host "  • Prometheus: http://localhost:9090"
        Write-Host "  • Grafana: http://localhost:3001 (admin/admin)"
    }
    
    Write-Host ""
    Write-Host "Management Commands:" -ForegroundColor Yellow
    Write-Host "  View logs:     docker-compose --profile prod logs -f"
    Write-Host "  Stop services: docker-compose --profile prod down"
    Write-Host "  Restart bot:   docker-compose --profile prod restart amiquinbot"
    Write-Host ""
    
    if ($EnableBackups) {
        Write-Host "Backup Configuration:" -ForegroundColor Cyan
        Write-Host "  • Database backups: Enabled (daily at 2:00 AM)"
        Write-Host "  • Configuration backups: Enabled"
        Write-Host "  • Retention: 30 days"
        Write-Host ""
    }
    
    Write-Host "Next Steps:" -ForegroundColor Yellow
    Write-Host "1. Verify all services are responding correctly"
    Write-Host "2. Test Discord bot functionality"
    Write-Host "3. Monitor logs for any errors"
    Write-Host "4. Set up external monitoring and alerting"
    Write-Host "5. Configure automated backups"
    Write-Host ""
    
    Write-Host "Environment: $Environment" -ForegroundColor Green
    Write-Host "Instance: $InstanceName" -ForegroundColor Green
    Write-Host "Database: $DatabaseType" -ForegroundColor Green
    Write-Host ""
}

# Main Deployment Process
try {
    Test-Prerequisites
    Set-ProductionEnvironment
    Invoke-ProductionBuild
    Start-ProductionServices
    Test-ServiceHealth
    Show-DeploymentSummary
    
    Write-Host "🎉 Production deployment completed successfully!" -ForegroundColor Green
    
} catch {
    Write-Host "❌ Deployment failed: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Check the logs above for more details." -ForegroundColor Yellow
    exit 1
}